writeLines("Generating Functions")
P <- correlate(col="SOLR_5", data=offset, selectedMethod="pearson")
# SCBH1_P_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson", correlationResults=P)
# SCBH1_P_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson", correlationResults=P)
# SCBH1_P_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson", correlationResults=P)
# SCBH1_P_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson", correlationResults=P)
# 
# S <- correlate(col="SOLR_4", data=SCBH1_Base, selectedMethod="spearman")
# SCBH1_S_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman", correlationResults=S)
# SCBH1_S_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman", correlationResults=S)
# SCBH1_S_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman", correlationResults=S)
# SCBH1_S_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman", correlationResults=S)
# 
# K <- correlate(col="SOLR_4", data=SCBH1_Base, selectedMethod="kendall")
# SCBH1_K_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall", correlationResults=K)
# SCBH1_K_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall", correlationResults=K)
# SCBH1_K_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall", correlationResults=K)
# SCBH1_K_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall", correlationResults=K)
# 
# P <- correlate(col="SOLR_4", data=SCSH1_Base, selectedMethod="pearson")
# SCSH1_P_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson", correlationResults=P)
# SCSH1_P_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson", correlationResults=P)
# SCSH1_P_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson", correlationResults=P)
# SCSH1_P_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson", correlationResults=P)
# 
# S <- correlate(col="SOLR_4", data=SCSH1_Base, selectedMethod="spearman")
# SCSH1_S_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman", correlationResults=S)
# SCSH1_S_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman", correlationResults=S)
# SCSH1_S_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman", correlationResults=S)
# SCSH1_S_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman", correlationResults=S)
# 
# K <- correlate(col="SOLR_4", data=SCSH1_Base, selectedMethod="kendall")
# SCSH1_K_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall", correlationResults=K)
# SCSH1_K_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall", correlationResults=K)
# SCSH1_K_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall", correlationResults=K)
# SCSH1_K_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall", correlationResults=K)
# 
# P <- correlate(col="SOLR_4", data=PLHH1_Base, selectedMethod="pearson")
# PLHH1_P_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson", correlationResults=P)
# PLHH1_P_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson", correlationResults=P)
# PLHH1_P_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson", correlationResults=P)
# PLHH1_P_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson", correlationResults=P)
# 
# S <- correlate(col="SOLR_4", data=PLHH1_Base, selectedMethod="spearman")
# PLHH1_S_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman", correlationResults=S)
# PLHH1_S_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman", correlationResults=S)
# PLHH1_S_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman", correlationResults=S)
# PLHH1_S_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman", correlationResults=S)
# 
# K <- correlate(col="SOLR_4", data=PLHH1_Base, selectedMethod="kendall")
# PLHH1_K_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall", correlationResults=K)
# PLHH1_K_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall", correlationResults=K)
# PLHH1_K_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall", correlationResults=K)
# PLHH1_K_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall", correlationResults=K)
# 
# rm(P)
# rm(S)
# rm(K)