source('SOLR_Predict.R')

currentWd <- getwd()

# Load Data
setwd("Data")

Buoy51201 <- filterColumns(loadCsv("51201-filtered.csv"))
AS839 <- filterColumns(loadCsv("AS839-filtered.csv"))
C0875 <- filterColumns(loadCsv("C0875-filtered.csv"))
D3665 <- filterColumns(loadCsv("D3665-filtered.csv"))
HOFH1 <- filterColumns(loadCsv("HOFH1-filtered.csv"))
KFWH1 <- filterColumns(loadCsv("KFWH1-filtered.csv"))
KTAH1 <- filterColumns(loadCsv("KTAH1-filtered.csv"))
MKHH1 <- filterColumns(loadCsv("MKHH1-filtered.csv"))
MKRH1 <- filterColumns(loadCsv("MKRH1-filtered.csv"))
MOKH1 <- filterColumns(loadCsv("MOKH1-filtered.csv"))
OFRH1 <- filterColumns(loadCsv("OFRH1-filtered.csv"))
OOUH1 <- filterColumns(loadCsv("OOUH1-filtered.csv"))
PHHI <- filterColumns(loadCsv("PHHI-filtered.csv"))
PHJR <- filterColumns(loadCsv("PHJR-filtered.csv"))
PHNG <- filterColumns(loadCsv("PHNG-filtered.csv"))
PHNL <- filterColumns(loadCsv("PHNL-filtered.csv"))
PLHH1 <- filterColumns(loadCsv("PLHH1-filtered.csv"))
SCBH1<- filterColumns(loadCsv("SCBH1-filtered.csv"))
SCSH1 <- filterColumns(loadCsv("SCSH1-filtered.csv"))
WNVH1 <- filterColumns(loadCsv("WNVH1-filtered.csv"))
WWFH1 <- filterColumns(loadCsv("WWFH1-filtered.csv"))

merged <- mergeDataFrames(SCBH1, Buoy51201, "51201")
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset <- dataOffset(5, "SOLR", merged)

gc()

setwd(currentWd)