if(file.exists("Data.RData")) {
  writeLines("Loading Data.RData")
  load("Data.RData")
} else {
  source("Load_Data.R")
}

source('SOLR_Predict.R')

writeLines("Quadrant 1")
merged <- SCBH1[SCBH1$DRCT > 90 & SCBH1$DRCT <= 180,]
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset_solr <- dataOffset(6, "SOLR", merged)
offset_solr_frac <- dataOffset(6, "SOLR_FRAC", merged)

save(merged, offset_solr, offset_solr_frac, file="Data_Quadrant_1.RData")
rm(merged)
rm(offset_solr)
rm(offset_solr_frac)
gc()

writeLines("Quadrant 2")
merged <- SCBH1[SCBH1$DRCT > 0 & SCBH1$DRCT <= 90,]
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset_solr <- dataOffset(6, "SOLR", merged)
offset_solr_frac <- dataOffset(6, "SOLR_FRAC", merged)

save(merged, offset_solr, offset_solr_frac, file="Data_Quadrant_2.RData")
rm(merged)
rm(offset_solr)
rm(offset_solr_frac)
gc()

writeLines("Quadrant 3")
merged <- SCBH1[SCBH1$DRCT > -90 & SCBH1$DRCT <= 0,]
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset_solr <- dataOffset(6, "SOLR", merged)
offset_solr_frac <- dataOffset(6, "SOLR_FRAC", merged)

save(merged, offset_solr, offset_solr_frac, file="Data_Quadrant_3.RData")
rm(merged)
rm(offset_solr)
rm(offset_solr_frac)
gc()

writeLines("Quadrant 4")
merged <- SCBH1[SCBH1$DRCT >= -180 & SCBH1$DRCT <= -90,]
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset_solr <- dataOffset(6, "SOLR", merged)
offset_solr_frac <- dataOffset(6, "SOLR_FRAC", merged)

save(merged, offset_solr, offset_solr_frac, file="Data_Quadrant_4.RData")
rm(merged)
rm(offset_solr)
rm(offset_solr_frac)
gc()