source('SOLR_Predict.R')

currentWd <- getwd()

# Load Data
setwd("Data")

Buoy51201 <- filterColumns(loadCsv("51201.csv"))
AS839 <- filterColumns(loadCsv("AS839.csv"))
C0875 <- filterColumns(loadCsv("C0875.csv"))
D3665 <- filterColumns(loadCsv("D3665.csv"))
HOFH1 <- filterColumns(loadCsv("HOFH1.csv"))
KFWH1 <- filterColumns(loadCsv("KFWH1.csv"))
KTAH1 <- filterColumns(loadCsv("KTAH1.csv"))
MKHH1 <- filterColumns(loadCsv("MKHH1.csv"))
MKRH1 <- filterColumns(loadCsv("MKRH1.csv"))
MOKH1 <- filterColumns(loadCsv("MOKH1.csv"))
OFRH1 <- filterColumns(loadCsv("OFRH1.csv"))
OOUH1 <- filterColumns(loadCsv("OOUH1.csv"))
PHHI <- filterColumns(loadCsv("PHHI.csv"))
PHJR <- filterColumns(loadCsv("PHJR.csv"))
PHNG <- filterColumns(loadCsv("PHNG.csv"))
PHNL <- filterColumns(loadCsv("PHNL.csv"))
PLHH1 <- filterColumns(loadCsv("PLHH1.csv"))
SCBH1<- filterColumns(loadCsv("SCBH1.csv"))
SCSH1 <- filterColumns(loadCsv("SCSH1.csv"))
WNVH1 <- filterColumns(loadCsv("WNVH1.csv"))
WWFH1 <- filterColumns(loadCsv("WWFH1.csv"))

merged <- mergeDataFrames(SCBH1, Buoy51201, "51201")
merged <- mergeDataFrames(merged, AS839, "AS839")
merged <- mergeDataFrames(merged, C0875, "C0875")
merged <- mergeDataFrames(merged, D3665, "D3665")
merged <- mergeDataFrames(merged, HOFH1, "HOFH1")
merged <- mergeDataFrames(merged, KFWH1, "KFWH1")
merged <- mergeDataFrames(merged, KTAH1, "KTAH1")
merged <- mergeDataFrames(merged, MKHH1, "MKHH1")
merged <- mergeDataFrames(merged, MKRH1, "MKRH1")
merged <- mergeDataFrames(merged, MOKH1, "MOKH1")
merged <- mergeDataFrames(merged, OFRH1, "OFRH1")
merged <- mergeDataFrames(merged, OOUH1, "OOUH1")
merged <- mergeDataFrames(merged, PHHI, "PHHI")
merged <- mergeDataFrames(merged, PHJR, "PHJR")
merged <- mergeDataFrames(merged, PHNG, "PHNG")
merged <- mergeDataFrames(merged, PHNL, "PHNL")
merged <- mergeDataFrames(merged, PLHH1, "PLHH1")
merged <- mergeDataFrames(merged, SCSH1, "SCSH1")
merged <- mergeDataFrames(merged, WNVH1, "WNVH1")
merged <- mergeDataFrames(merged, WWFH1, "WWFH1")

offset_solr <- dataOffset(6, "SOLR", merged)
offset_solr_frac <- dataOffset(6, "SOLR_FRAC", merged)

gc()

setwd(currentWd)

save.image("Data.RData")