source('SOLR_Predict.R')

writeLines("Loading data...")
source('Load_Data.R')
# 
# writeLines("Doing correlations...")
# logCorrelations(col="SOLR_4", data=SCBH1_Base, filePrefix="SCBH1", getTop=T, numTop=20)
# logCorrelations(col="SOLR_4", data=SCSH1_Base, filePrefix="SCSH1", getTop=T, numTop=20)
# logCorrelations(col="SOLR_4", data=PLHH1_Base, filePrefix="PLHH1", getTop=T, numTop=20)
# 
# writeLines("Testing Night Day Thresholds...")
# sink("SCBH1_NightDay_Thresh.out")
# testNightDayThreshold(data=SCBH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
# sink()
# sink("SCSH1_NightDay_Thresh.out")
# testNightDayThreshold(data=SCSH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
# sink()
# sink("PLHH1_NightDay_Thresh.out")
# testNightDayThreshold(data=PLHH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
# sink()
# 
# writeLines("Testing Night Day Intervals...")
# sink("SCBH1_NightDay_Interval.out")
# testNightDayIntervals(data=SCBH1_Base, solrColName="SOLR_4", checkAnn=T)
# sink()
# sink("SCSH1_NightDay_Interval.out")
# testNightDayIntervals(data=SCSH1_Base, solrColName="SOLR_4", checkAnn=T)
# sink()
# sink("PLHH1_NightDay_Interval.out")
# testNightDayIntervals(data=PLHH1_Base, solrColName="SOLR_4", checkAnn=T)
# sink()
# 
# writeLines("Testing Solr Cut Size")
# sink("SCBH1_P_Solr_Cut.out")
# testSolrCuts(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + FT_3 + SOLR_2 + SCSH1_FT_3", checkAnn=T)
# sink()
# sink("SCBH1_S_Solr_Cut.out")
# testSolrCuts(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + SOLR_2 + SCSH1_SOLR_2 + VOLT_3", checkAnn=T)
# sink()
# sink("SCSH1_P_Solr_Cut.out")
# testSolrCuts(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + FT_3 + TMPF_3 + SOLR_2 + SCBH1_FT_3", checkAnn=T)
# sink()
# sink("SCSH1_S_Solr_Cut.out")
# testSolrCuts(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + FT_3 + SCBH1_FT_3 + TMPF_3", checkAnn=T)
# sink()
# sink("PLHH1_P_Solr_Cut.out")
# testSolrCuts(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + WWFH1_VOLT_3 + SOLR_2 + TMPF_3 + WWFH1_TMPF_3", checkAnn=T)
# sink()
# sink("PLHH1_S_Solr_Cut.out")
# testSolrCuts(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + WWFH1_VOLT_3 + PHJR_TMPF_3 + WWFH1_TMPF_3", checkAnn=T)
# sink()

writeLines("Generating Functions")
SCBH1_P_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson")
SCBH1_P_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson")
SCBH1_P_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson")
SCBH1_P_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson")

SCBH1_S_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman")
SCBH1_S_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman")
SCBH1_S_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman")
SCBH1_S_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman")

SCBH1_K_5 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall")
SCBH1_K_10 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall")
SCBH1_K_15 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall")
SCBH1_K_20 <- makeTopFunction(data=SCBH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall")

SCSH1_P_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson")
SCSH1_P_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson")
SCSH1_P_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson")
SCSH1_P_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson")

SCSH1_S_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman")
SCSH1_S_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman")
SCSH1_S_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman")
SCSH1_S_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman")

SCSH1_K_5 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall")
SCSH1_K_10 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall")
SCSH1_K_15 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall")
SCSH1_K_20 <- makeTopFunction(data=SCSH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall")

PLHH1_P_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="pearson")
PLHH1_P_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="pearson")
PLHH1_P_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="pearson")
PLHH1_P_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="pearson")

PLHH1_S_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="spearman")
PLHH1_S_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="spearman")
PLHH1_S_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="spearman")
PLHH1_S_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="spearman")

PLHH1_K_5 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=5, selectedMethod="kendall")
PLHH1_K_10 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=10, selectedMethod="kendall")
PLHH1_K_15 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=15, selectedMethod="kendall")
PLHH1_K_20 <- makeTopFunction(data=PLHH1_Base, colName="SOLR_4", topThreshold=20, selectedMethod="kendall")

writeLines("Testing Solr Intervals")
writeLines("SCBH1")
sink("SCBH1_P_5_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_P_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_S_5_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_S_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_K_5_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_K_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCBH1_P_10_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_P_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_S_10_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_S_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_K_10_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_K_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCBH1_P_15_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_P_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_S_15_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_S_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_K_15_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_K_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCBH1_P_20_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_P_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_S_20_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_S_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCBH1_K_20_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=SCBH1_K_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

writeLines("SCSH1")

sink("SCSH1_P_5_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_P_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_S_5_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_S_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_K_5_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_K_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCSH1_P_10_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_P_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_S_10_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_S_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_K_10_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_K_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCSH1_P_15_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_P_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_S_15_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_S_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_K_15_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_K_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("SCSH1_P_20_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_P_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_S_20_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_S_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("SCSH1_K_20_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=SCSH1_K_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

writeLines("PLHH1")

sink("PLHH1_P_5_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_P_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_S_5_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_S_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_K_5_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_K_5, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("PLHH1_P_10_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_P_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_S_10_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_S_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_K_10_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_K_10, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("PLHH1_P_15_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_P_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_S_15_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_S_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_K_15_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_K_15, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

sink("PLHH1_P_20_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_P_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_S_20_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_S_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()
sink("PLHH1_K_20_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=PLHH1_K_20, checkNb=T, checkAnn=T)#, checkRandomForest=T)
sink()

# sink("SCBH1_A_Solr_Interval.out")
# testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction=makeFullModelFunction(data=SCBH1_Base, colName="SOLR_4"))#, checkAnn=T, checkRandomForest=T)
# sink()
# 
# # START HERE
# sink("SCSH1_A_Solr_Interval.out")
# testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction=makeFullModelFunction(data=SCSH1_Base, colName="SOLR_4"))#, checkAnn=T, checkRandomForest=T)
# sink()
# sink("PLHH1_A_Solr_Interval.out")
# testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction=makeFullModelFunction(data=PLHH1_Base, colName="SOLR_4"))#, checkAnn=T, checkRandomForest=T)
# sink()



writeLines("Baseline tests")

writeLines("SCBH1")

sink("SCBH1_Base_P_5.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_P_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_P_10.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_P_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_P_15.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_P_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_P_20.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_P_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_S_5.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_S_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_S_10.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_S_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_S_15.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_S_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_S_20.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_S_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_K_5.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_K_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_K_10.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_K_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_K_15.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_K_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

sink("SCBH1_Base_K_20.out")
testSolr(data=SCBH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCBH1_K_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCBH1$SOLR, na.rm=T))
sink()

writeLines("SCSH1")

sink("SCSH1_Base_P_5.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_P_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_P_10.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_P_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_P_15.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_P_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_P_20.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_P_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_S_5.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_S_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_S_10.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_S_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_S_15.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_S_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_S_20.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_S_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_K_5.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_K_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_K_10.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_K_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_K_15.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_K_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

sink("SCSH1_Base_K_20.out")
testSolr(data=SCSH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=SCSH1_K_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(SCSH1$SOLR, na.rm=T))
sink()

writeLines("PLHH1")

sink("PLHH1_Base_P_5.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_P_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_P_10.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_P_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_P_15.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_P_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_P_20.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_P_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_S_5.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_S_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_S_10.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_S_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_S_15.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_S_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_S_20.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_S_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_K_5.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_K_5, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_K_10.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_K_10, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_K_15.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_K_15, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()

sink("PLHH1_Base_K_20.out")
testSolr(data=PLHH1_Base, intervalSize=1440, colName="SOLR_4", modelFunction=PLHH1_K_20, numCuts=1000, checkNb=T, checkAnn=T, mean=mean(PLHH1$SOLR, na.rm=T))
sink()