source('SOLR_Predict.R')

writeLines("Loading data...")
source('Load_Data.R')

writeLines("Doing correlations...")
logCorrelations(col="SOLR_4", data=SCBH1_Base, filePrefix="SCBH1", getTop=T, numTop=20)
logCorrelations(col="SOLR_4", data=SCSH1_Base, filePrefix="SCSH1", getTop=T, numTop=20)
logCorrelations(col="SOLR_4", data=PLHH1_Base, filePrefix="PLHH1", getTop=T, numTop=20)

writeLines("Testing Night Day Thresholds...")
sink("SCBH1_NightDay_Thresh.out")
testNightDayThreshold(data=SCBH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
sink()
sink("SCSH1_NightDay_Thresh.out")
testNightDayThreshold(data=SCSH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
sink()
sink("PLHH1_NightDay_Thresh.out")
testNightDayThreshold(data=PLHH1_Base, solrColName="SOLR_4", maxThreshold=20, checkAnn=T)
sink()

writeLines("Testing Night Day Intervals...")
sink("SCBH1_NightDay_Interval.out")
testNightDayIntervals(data=SCBH1_Base, solrColName="SOLR_4", checkAnn=T)
sink()
sink("SCSH1_NightDay_Interval.out")
testNightDayIntervals(data=SCSH1_Base, solrColName="SOLR_4", checkAnn=T)
sink()
sink("PLHH1_NightDay_Interval.out")
testNightDayIntervals(data=PLHH1_Base, solrColName="SOLR_4", checkAnn=T)
sink()

writeLines("Testing Solr Cut Size")
sink("SCBH1_P_Solr_Cut.out")
testSolrCuts(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + FT_3 + SOLR_2 + SCSH1_FT_3")#, checkAnn=T)
sink()
sink("SCBH1_S_Solr_Cut.out")
testSolrCuts(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + SOLR_2 + SCSH1_SOLR_2 + VOLT_3")#, checkAnn=T)
sink()
sink("SCSH1_P_Solr_Cut.out")
testSolrCuts(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + FT_3 + TMPF_3 + SOLR_2 + SCBH1_FT_3")#, checkAnn=T)
sink()
sink("SCSH1_S_Solr_Cut.out")
testSolrCuts(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + FT_3 + SCBH1_FT_3 + TMPF_3")#, checkAnn=T)
sink()
sink("PLHH1_P_Solr_Cut.out")
testSolrCuts(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + WWFH1_VOLT_3 + SOLR_2 + TMPF_3 + WWFH1_TMPF_3")#, checkAnn=T)
sink()
sink("PLHH1_S_Solr_Cut.out")
testSolrCuts(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + WWFH1_VOLT_3 + PHJR_TMPF_3 + WWFH1_TMPF_3")#, checkAnn=T)
sink()

writeLines("Testing Solr Intervals")
sink("SCBH1_P_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + FT_3 + SOLR_2 + SCSH1_FT_3")#, checkAnn=T, checkRandomForest=T)
sink()
sink("SCBH1_S_Solr_Interval.out")
testSolrIntervals(data=SCBH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SCSH1_SOLR_3 + SOLR_2 + SCSH1_SOLR_2 + VOLT_3")#, checkAnn=T, checkRandomForest=T)
sink()
sink("SCSH1_P_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + FT_3 + TMPF_3 + SOLR_2 + SCBH1_FT_3")#, checkAnn=T, checkRandomForest=T)
sink()
sink("SCSH1_S_Solr_Interval.out")
testSolrIntervals(data=SCSH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + FT_3 + SCBH1_FT_3 + TMPF_3")#, checkAnn=T, checkRandomForest=T)
sink()
sink("PLHH1_P_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + WWFH1_VOLT_3 + SOLR_2 + TMPF_3 + WWFH1_TMPF_3")#, checkAnn=T, checkRandomForest=T)
sink()
sink("PLHH1_S_Solr_Interval.out")
testSolrIntervals(data=PLHH1_Base, colName="SOLR_4", modelFunction="SOLR_4 ~ SOLR_3 + SOLR_2 + WWFH1_VOLT_3 + PHJR_TMPF_3 + WWFH1_TMPF_3")#, checkAnn=T, checkRandomForest=T)
sink()